```{r}
if ( !require(duckdb) ) install.packages("duckdb")

library(duckdb)

# インメモリデータベースに接続
#con <- dbConnect(duckdb())

# データベースに接続
# (DBを他のプロセスと共有するときは、read_only = TRUEにし書き込みを禁止する。)
con <- dbConnect(duckdb(), dbdir = 'a.duckdb', read_only = FALSE)

# データベースにあるテーブルを表示
dbListTables(con)

# 入力するデータを作成
d <- data.frame(name   = c('Taro', 'Jiro'),
                salary = c(600, 550))

# 既にテーブルが存在している場合は削除
#if ( dbExistsTable(con, 'items') ) dbRemoveTable(con, 'items')

# データベースにテーブルを作成
#【オプション】追記モード： append = T、#上書きモード： overwrite = T
dbWriteTable(con, 'items', d, append = T)

# テーブルからデータを取得
res <- dbGetQuery(con, "SELECT * FROM items")

# 取得したデータを表示
# 本コードでは追記モードにしているのでプログラム実行のたびに同じレコード追加される。
print(res)

dbDisconnect(con, shutdown = TRUE)

library(nycflights13)
data("flights", package = "nycflights13") # データの取得
```


```{r}
library(tidyverse)

d <- data.frame(
  name = c("太郎", "花子", "三郎", "良子", "次郎", "桜子", "四郎", "松子", "愛子"),
  school = c("南", "南", "南", "南", "南", "東", "東", "東", "東"),
  teacher = c("竹田", "竹田", "竹田", "竹田",  "佐藤", "佐藤", "佐藤", "鈴木", "鈴木"),
  gender = c("男", "女", "男", "女", "男", "女", "男", "女", "女"),
  math = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
  reading = c(1, 5, 2, 4, 5, 4, 1, 5, 4) )

library(DT)
datatable(d)
```




```{r}
#１
d |> select (name,math)
```

```{r}
#２
d |> select(-gender)
```
```{r}
#3
d |> slice(3:6)
```
```{r}
#4
d |> arrange(name)
```
```{r}
#5
d |> arrange(desc(math))
```
```{r}
#6
d |> arrange(desc(math),desc(reading))

```
```{r}
#7
d |>select(name,reading)
```
```{r}
#8
d |>　summarize(math_mean　= mean(math))
```
```{r}
#9
d|> group_by(teacher) |> summarise(math_mean = mean(math))
```


```{r}
#10
d |> filter(gender == '女')　|> select(name,gender,math,reading)
```
```{r}
#11
d |> filter(school == '南',gender == '男') |> select(name,gender,reading)
```
```{r}
#12
d |> group_by(teacher) |> filter(n() >= 3) 

```

```{r}
#13
d |> mutate(total = math + reading)
```
```{r}
#14
d |>  mutate(math100 = math * (100 / max(math)))
```

